### ISSUE TITLE
Recipe Conflict Issue

### ISSUE THREAD

**Issue by Nicole-Evermore** [kreezxil/Better-With-Minecolonies#1]
The Peony recipe seems to be coded as shapeless and of higher priority than the rose bush, as any attempt to craft the rose bush instead returns Peony. Doesn't seem to conflict with any of the other recipes. I'm using version 1.6.7 of the mod.

Found this issue in the 'Janky Skyblock' pack.

**Comment by kreezxil** [comment]
ok, cool. I"ll make the correction. thank you for your report.

**Comment by kreezxil** [comment]
fixed in 1.7.8
